version: "3.7"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.7@sha256:56d4304302cb2bb87a5ebe7b8c3d2f4caf47dcb1ddb8ac3613920d89440961df
    restart: unless-stopped
    container_name: plex
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      PLEX_CLAIM: "${PLEX_CLAIM}"
    networks:
      default:
        ipv4_address: "172.18.0.4"
    volumes:
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/media"
    tmpfs:
      - "/tmp"
    


  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.10.1-develop@sha256:1b36dbcc95eefba1dbd66000c551e7207c786c9f7040a676a5c386ab5db082bb
    restart: unless-stopped
    container_name: prowlarr    
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped  
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      default:
        ipv4_address: 172.18.0.9
    volumes:
      - "${CONFIG_DIR}/sabnzbd:/config"
      - "${DOWNLOADS_DIR}:/downloads"


  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:dbd380e7dbd9eb79cc488bd42d93336b47a2d3c3b6dec56bdb1c314ee614f536
    restart: unless-stopped
    container_name: sonarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - sabnzbd

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:5.0.3@sha256:9d963b1a7cf228904a0d17ad99e5fe2aeb91c17432dbe166ba1950664e3a9f86
    restart: unless-stopped
    container_name: radarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - sabnzbd
  
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    container_name: readarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/readarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    networks:
      - default
    links:
      - nzbhydra
      - sabnzbd    
  
  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:4.7.6@sha256:ded588be5b2b0f405a7f34ba7279653e8fe288d0eea75b6d7de726cc765e7733
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/nzbhydra:/config"
      - "${DOWNLOADS_DIR}:/downloads"

  # https://docs.overseerr.dev/getting-started/installation
  # https://hub.docker.com/r/linuxserver/overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:1a7a05fea6e87a89d073166066108d8070aebf21c4a554ab37142e139a5cbc94
    restart: unless-stopped
    container_name: overseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    links:
      - sonarr
      - radarr
      - plex
    networks:
      - default

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped      
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/calibre:/config
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"      
    networks:
      - default      




